Repository ultrajson/ultrajson, pull requests merged in 2020-03, with the labels that each got.

#362 Tests: Remove unused, unmaintained blist
  .github/workflows/test.yml
  .travis.yml
  tests/benchmark.py
Labels: testing

#361 Less Travis
  .pre-commit-config.yaml
  .travis.yml
  README.rst
Labels: testing

#363 Test with pytest
  .github/workflows/test.yml
  .travis.yml
  tests/test_ujson.py
Labels: testing

#364 Deploy from GitHub Actions instead of Travis CI
  .github/workflows/deploy.yml
  .travis.yml
Labels: release

#365 Use Release Drafter to draft releases
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
Labels: release

#257 Fix a couple of memory leaks.
  python/objToJSON.c
Labels: changelog: Fixed

#353 Fix reference counting bug for dict values
  python/objToJSON.c
  tests/test_ujson.py
Labels: changelog: Fixed

#281 Reduce default buffer on stack size
  lib/ultrajson.h
Labels: changelog: Changed

#370 Fix Windows build and test Python 3.5-3.8 on Windows
  .github/workflows/lint.yml
  .github/workflows/test.yml
  lib/ultrajson.h
Labels: Windows, bug, changelog: Fixed

#379 Add script to build wheels with manylinux
  scripts/build-manylinux.py
Labels: release

#381 Tests: Convert to pytest
  setup.cfg
  tests/test_ujson.py
Labels: bug, changelog: skip, testing

#382 Fix "�� is not JSON serializable" on Python 3
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  python/objToJSON.c
  tests/test_ujson.py
Labels: bug, changelog: Fixed

#389 remove double_precision and precise_float from help text
  python/ujson.c
Labels: documentation

#386 Add release checklist
  RELEASING.md
Labels: changelog: skip, documentation, release

#388 GHA: Test on Python 3.9-dev
  .github/workflows/test.yml
Labels: changelog: skip, testing

#391 Add issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog: skip

#394 Decrease dict key reference.
  python/objToJSON.c
  tests/test_ujson.py
Labels: bug, changelog: Fixed

#395 Update benchmarking
  .github/workflows/benchmark.yml
  README.rst
  tests/benchmark.py
Labels: changelog: Changed

#396 Fix TestPyPI deploy
  .github/workflows/deploy.yml
Labels: changelog: skip, release, testing

#397 Drop legacy distutils in setup.py
  setup.cfg
  setup.py
Labels: changelog: Changed

#399 Specify setuptools_scm config in pyproject.toml
  pyproject.toml
Labels: changelog: Changed
