Repository ultrajson/ultrajson, pull requests merged in 2020-09, with the labels that each got.

#422 Add build step to deploy-wheels.yml that builds aarch64 wheels
  .github/workflows/deploy-wheels.yml
  scripts/Dockerfile_aarch64
Labels: changelog: Added, enhancement, release

#417 Make ujson PEP 384 compliant
  python/JSONtoObj.c
  python/objToJSON.c
  python/ujson.c
Labels: changelog: Added

#423 Build Linux wheels in parallel
  .github/workflows/deploy-wheels.yml
Labels: changelog: skip, release

#427 Update code samples in README
  README.rst
Labels: changelog: Fixed, documentation
