Repository ultrajson/ultrajson, pull requests merged in 2020-11, with the labels that each got.

#439 Fix dealing with None types
  python/objToJSON.c
  tests/test_ujson.py
Labels: bug, changelog: Fixed

#443 Toward matching Python standard library output for float
  lib/ultrajson.h
  python/objToJSON.c
  tests/test_ujson.py
Labels: changelog: Changed

#438 Replace 3.9-dev with 3.9 in .travis.yml to use Python 3.9 final
  .travis.yml
Labels: changelog: Changed, testing

#442 Fix errors on reading long decimal floats
  lib/ultrajsondec.c
  tests/test_ujson.py
Labels: changelog: Fixed
