Repository ultrajson/ultrajson, pull requests merged in 2020-06, with the labels that each got.

#410 Update release checklist
  .pre-commit-config.yaml
  RELEASING.md
Labels: changelog: skip, documentation

#413 PyPy3 test fixes
  .github/workflows/test.yml
  tests/test_ujson.py
Labels: testing

#414 Simplify and update GitHub Actions CI config
  .github/workflows/benchmark.yml
  .github/workflows/deploy-wheels.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: changelog: skip, testing
