Repository ultrajson/ultrajson, pull requests merged in 2021-12, with the labels that each got.

#491 Use cibuildwheel to build wheels.
  .github/workflows/deploy-wheels-linux.yml
  .github/workflows/deploy-wheels-windows-macos.yml
  .github/workflows/deploy.yml
  scripts/build-manylinux-wheels.sh
  scripts/build-manylinux.py
Labels: changelog: Added

#490 Drop support for soon-EOL Python 3.6
  .github/workflows/benchmark.yml
  .github/workflows/deploy.yml
  .github/workflows/labels.yml
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  pyproject.toml
  setup.cfg
Labels: changelog: Removed

#492 Install Twine to upload to PyPI
  .github/workflows/deploy.yml
Labels: changelog: Fixed

#493 Strip debugging symbols from Linux binaries
  setup.py
Labels: changelog: Changed
