Repository ultrajson/ultrajson, pull requests merged in 2021-09, with the labels that each got.

#471 Rename master to main
  .github/workflows/benchmark.yml
  .github/workflows/deploy-wheels.yml
  .github/workflows/deploy.yml
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
  README.rst
  RELEASING.md
Labels: changelog: Changed

#470 Add a default keyword argument to dumps
  python/objToJSON.c
  tests/test_ujson.py
Labels: changelog: Added

#472 Add support for Python 3.10
  .github/workflows/deploy-wheels.yml
  .github/workflows/test.yml
  scripts/build-manylinux-wheels.sh
  scripts/build-manylinux.py
  setup.py
Labels: changelog: Added

#473 Wheel building updates
  .github/workflows/deploy-wheels-linux.yml
  .github/workflows/deploy-wheels-windows-macos.yml
  scripts/Dockerfile_aarch64
  scripts/build-manylinux-wheels.sh
Labels: changelog: Changed

#476 Build wheels for musl Linux (musllinux_1_1_x86_64)
  .github/workflows/deploy-wheels-linux.yml
Labels: changelog: Added

#475 Build PyPy3 manylinux wheels
  .github/workflows/deploy-wheels-linux.yml
  .github/workflows/deploy-wheels-windows-macos.yml
Labels: changelog: Added

#477 Use declarative setup metadata
  .pre-commit-config.yaml
  setup.cfg
  setup.py
Labels: changelog: Changed

#479 Replace README.rst with Markdown
  MANIFEST.in
  README.md
  README.rst
  setup.cfg
  tests/benchmark.py
Labels: changelog: Changed

#478 Build wheels for musl aarch64 (aka ARM) Linux (musllinux_1_1_aarch64)
  .github/workflows/deploy-wheels-linux.yml
Labels: changelog: Added

#481 Build 32-bit wheels for Windows
  .github/workflows/deploy-wheels-windows-macos.yml
Labels: Windows, changelog: Added
