Repository ultrajson/ultrajson, pull requests merged in 2022-02, with the labels that each got.

#499 Travis CI: Test on Python 3.10 release rather than alpha version
  .travis.yml
Labels: changelog: skip

#498 Add JSONDecodeError
  python/JSONtoObj.c
  python/ujson.c
  python/ujson.h
  tests/test_ujson.py
Labels: changelog: Added

#500 Verify that JSONDecodeError is an actual subclass of ValueError, not just an alias
  tests/test_ujson.py
Labels: changelog: skip

#508 Support dynamically linking against system double-conversion library
  README.md
  setup.py
Labels: changelog: Added

#509 Remove dead code that used to handle the separate int type in Python 2
  lib/ultrajson.h
  lib/ultrajsonenc.c
  python/objToJSON.c
Labels: changelog: Fixed

#510 simplify exception handling on integer overflow
  python/objToJSON.c
Labels: changelog: Fixed
