Repository ultrajson/ultrajson, pull requests merged in 2022-06, with the labels that each got.

#544 Integer parsing: always detect overflows
  lib/ultrajsondec.c
  tests/test_ujson.py
Labels: changelog: Fixed

#547 Reduce CI matrix: test Ubuntu on all Pythons, and the others on a single Python
  .github/workflows/test.yml
  tests/test_ujson.py
Labels: testing, changelog: skip

#549 Fix memory leak on encoding errors when the buffer was resized
  lib/ultrajsonenc.c
  python/objToJSON.c
  tests/memory.py
  tests/test_ujson.py
Labels: changelog: Fixed

#554 Deploy workflow: Add colour to CI output
  .github/workflows/deploy.yml
Labels: testing, changelog: skip

#551 Move cross-architecture testing to GitHub Actions.
  .github/workflows/test.yml
  .travis.yml
  README.md
  RELEASING.md
Labels: testing, changelog: skip

#553 Re-enable testing on PyPy for all platforms.
  .github/workflows/test.yml
  tests/test_ujson.py
Labels: testing, changelog: skip

#548 Add support for arbitrary size integers
  lib/ultrajson.h
  lib/ultrajsondec.c
  python/JSONtoObj.c
  python/objToJSON.c
  tests/test_ujson.py
Labels: changelog: Added

#555 Replace `wchar_t` string decoding implementation with a `uint32_t`-based one
  lib/ultrajson.h
  lib/ultrajsondec.c
  python/JSONtoObj.c
  tests/test_ujson.py
Labels: changelog: Fixed
