Repository ultrajson/ultrajson, pull requests merged in 2022-04, with the labels that each got.

#515 Upgrade Black to fix Click
  .pre-commit-config.yaml
  tests/test_ujson.py
Labels: testing, changelog: Fixed

#514 Support parsing NaN, Infinity and -Infinity
  lib/ultrajson.h
  lib/ultrajsondec.c
  python/JSONtoObj.c
  tests/test_ujson.py
Labels: enhancement, changelog: Added

#524 Fix ref counting on repeated default function calls
  python/objToJSON.c
  tests/test_ujson.py
Labels: changelog: Fixed

#521 Fix memory leak dumping on non-string dict keys
  python/objToJSON.c
  tests/test_ujson.py
Labels: changelog: Fixed

#528 Add test for key ref counts with sort_keys enabled
  tests/test_ujson.py
Labels: testing, changelog: skip

#527 Add ref count checks to fuzz tests
  tests/fuzz.py
Labels: changelog: skip

#526 Fix segmentation fault when an exception is raised while converting a dict key to a string
  python/objToJSON.c
  tests/test_ujson.py
Labels: changelog: Fixed

#531 Fix segmentation faults when errors occur while handling unserialisable objects
  python/objToJSON.c
  tests/test_ujson.py
Labels: changelog: Fixed

#529 Add and fix debug memory checks for all buffer appends on encoding
  lib/ultrajsonenc.c
Labels: changelog: skip

#533 Benchmark refactor - argparse CLI
  tests/benchmark.py
Labels: changelog: Changed

#534 Benchmark CI fixes
  .github/workflows/benchmark.yml
  tests/benchmark.py
Labels: changelog: skip
